apiVersion: v1
kind: ReplicationController
metadata:
    name: ase-v0-0-1
spec:
  replicas: 1
  selector:
    name: ase
    version: v0.0.1
  template:
    metadata:
      labels:
        name: ase
        version: v0.0.1
      annotations:
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: ase
          image: quay.io/berset/aws-spotprice-exporter:v0.0.1
          ports:
            - containerPort: 9090
              name: metrics
          resources:
              limits:
                  memory: "50Mi"
